AppGestionEMS/AppGestionEMS/Controllers/CursosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario1")]

    public class CursosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Cursos
        public ActionResult Index()
        {
            return View(db.Cursos.ToList());
        }

        // GET: Cursos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursos cursos = db.Cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            return View(cursos);
        }

        // GET: Cursos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cursos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Cod_Curso,Actual")] Cursos cursos)
        {
            if (ModelState.IsValid)
            {
                db.Cursos.Add(cursos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cursos);
        }

        // GET: Cursos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursos cursos = db.Cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            return View(cursos);
        }

        // POST: Cursos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Cod_Curso,Actual")] Cursos cursos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cursos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cursos);
        }

        // GET: Cursos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cursos cursos = db.Cursos.Find(id);
            if (cursos == null)
            {
                return HttpNotFound();
            }
            return View(cursos);
        }

        // POST: Cursos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cursos cursos = db.Cursos.Find(id);
            db.Cursos.Remove(cursos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Controllers/EvaluacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario2")]

    public class EvaluacionesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Evaluaciones
        public ActionResult Index()
        {
            var evaluaciones = db.Evaluaciones.Include(e => e.Curso).Include(e => e.User);
            return View(evaluaciones.ToList());
        }

        // GET: Evaluaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso");
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname");

            return View();
        }

        // POST: Evaluaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CursoId,UserId,Convocatoria,Trabajo1,Trabajo2,Trabajo3,Test,Practica")] Evaluaciones evaluaciones)
        {
            if (ModelState.IsValid)
            {
                db.Evaluaciones.Add(evaluaciones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", evaluaciones.UserId);
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname", evaluaciones.UserId);

            return View(evaluaciones);
        }

        // POST: Evaluaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CursoId,UserId,Convocatoria,Trabajo1,Trabajo2,Trabajo3,Test,Practica")] Evaluaciones evaluaciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evaluaciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Name", evaluaciones.UserId);
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }

        // POST: Evaluaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            db.Evaluaciones.Remove(evaluaciones);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Controllers/MisEvaluacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;
using Microsoft.AspNet.Identity;


namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario3")]

    public class MisEvaluacionesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MisEvaluaciones
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();
            var evaluaciones = db.Evaluaciones.Include(e => e.Curso).Include(e => e.User).Where(p => p.UserId == currentUserId); ;
            return View(evaluaciones.ToList());
        }

        // GET: MisEvaluaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Views/MisEvaluaciones/Create.cshtml
@model AppGestionEMS.Models.Evaluaciones

@{
    ViewBag.Title = "Añadir evluación";
}
<div class="container container-fluid">

    <h2>Añadir evluación</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.CursoId, "CursoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CursoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CursoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Convocatoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Convocatoria, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Convocatoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Test, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Test, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Test, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Practica, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Practica, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Practica, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-check-square-o fa-lg"></i> Añadir
                    </button>
                </div>
            </div>
        </div>
    }

    <div>
        <span>
            <a href="@Url.Action("Index", "Evaluaciones" )" class="btn btn-primary">
                <span class="fa fa-undo fa-lg"></span>
                Volver a la lista
            </a>
        </span>
    </div>
</div>
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AppGestionEMS/AppGestionEMS/Views/MisEvaluaciones/Delete.cshtml
@model AppGestionEMS.Models.Evaluaciones

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evaluaciones</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Curso.Cod_Curso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Curso.Cod_Curso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.User.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.NameSurname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Convocatoria)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Convocatoria)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajo1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajo1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajo2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajo2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Trabajo3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Trabajo3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Test)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Test)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Practica)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Practica)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AppGestionEMS/AppGestionEMS/Views/MisEvaluaciones/Details.cshtml
@model AppGestionEMS.Models.Evaluaciones

@{
    ViewBag.Title = "Detalles mi evaluación";
}
<div class="container container-fluid">
    <h2>Detalles mi evaluación</h2>

    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Curso.Cod_Curso)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Curso.Cod_Curso)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.User.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.User.NameSurname)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Convocatoria)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Convocatoria)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Trabajo1)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Trabajo1)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Trabajo2)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Trabajo2)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Trabajo3)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Trabajo3)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Test)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Test)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Practica)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Practica)
            </dd>

        </dl>
    </div>
    <p>
          <span>
            <a href="@Url.Action("Index", "MisEvaluaciones")" class="btn btn-primary">
                <span class="fa fa-undo fa-lg"></span>
                Volver a la lista
            </a>
        </span>
    </p>
</div>

AppGestionEMS/AppGestionEMS/Views/MisEvaluaciones/Edit.cshtml
@model AppGestionEMS.Models.Evaluaciones

@{
    ViewBag.Title = "Edit Este no se usa";
}
<div class="container container-fluid">

    <h2>Edit</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Evaluaciones</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.CursoId, "CursoId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CursoId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CursoId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Convocatoria, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EnumDropDownListFor(model => model.Convocatoria, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Convocatoria, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo1, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo1, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo1, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo2, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo2, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo2, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Trabajo3, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Trabajo3, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Trabajo3, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Test, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Test, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Test, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Practica, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Practica, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Practica, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        <span>
            <a href="@Url.Action("Index", "Cursos" )" class="btn btn-primary">
                <span class="fa fa-undo fa-lg"></span>
                Volver a la lista
            </a>
        </span> 
    </div>
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

AppGestionEMS/AppGestionEMS/Views/MisEvaluaciones/Index.cshtml
@model IEnumerable<AppGestionEMS.Models.Evaluaciones>

@{
    ViewBag.Title = "Mis evaluaciones";
}
<div class="container container-fluid">

    <h2>Mis evaluaciones</h2>


    <table id="etsisitravel" class="table table-striped table-hover table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Curso.Cod_Curso)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.User.Name)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Convocatoria)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Trabajo1)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Trabajo2)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Trabajo3)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Test)
                </th>
                <th class="bg-primary">
                    @Html.DisplayNameFor(model => model.Practica)
                </th>
                <th class="bg-primary"></th>
            </tr>
        </thead> 
        

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Curso.Cod_Curso)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.User.NameSurname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Convocatoria)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trabajo1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trabajo2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Trabajo3)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Test)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Practica)
                </td>
                <td>
                    <span>
                        <a href="@Url.Action("Details", "MisEvaluaciones", new { id = item.Id })" class="btn btn-primary">
                            <span class="fa fa-eye fa-lg"></span>
                            Detalles
                        </a>
                    </span>
                </td>
            </tr>
        }

    </table>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
            $('#etsisitravel').dataTable({
                "columnDefs": [
                  { "width": "5%", "targets": [0] },
                  { "width": "40%", "targets": [1] },
                  { "width": "5%", "targets": [2] },
                  { "width": "5%", "targets": [3, 4, 5, 6, 7] },
                  { "width": "20%", "targets": "_all" },
                  { "className": "text-center", "targets": "_all" }
                ],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.16/i18n/Spanish.json"
                }
            });
    </script>
}