AppGestionEMS/AppGestionEMS/Controllers/AsignacionDocentesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario1")]

    public class AsignacionDocentesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AsignacionDocentes
        public ActionResult Index()
        {
            var asignacionDocentes = db.AsignacionDocentes.Include(a => a.Curso).Include(a => a.GrupoClases).Include(a => a.User);
            return View(asignacionDocentes.ToList());
        }

        // GET: AsignacionDocentes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignacionDocentes asignacionDocentes = db.AsignacionDocentes.Find(id);
            if (asignacionDocentes == null)
            {
                return HttpNotFound();
            }
            return View(asignacionDocentes);
        }

        // GET: AsignacionDocentes/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso");
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo");
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname");



            return View();
        }

        // POST: AsignacionDocentes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CursoId,GrupoClasesId,UserId")] AsignacionDocentes asignacionDocentes)
        {
            if (ModelState.IsValid)
            {
                db.AsignacionDocentes.Add(asignacionDocentes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", asignacionDocentes.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", asignacionDocentes.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", asignacionDocentes.UserId);
            return View(asignacionDocentes);
        }

        // GET: AsignacionDocentes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignacionDocentes asignacionDocentes = db.AsignacionDocentes.Find(id);
            if (asignacionDocentes == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", asignacionDocentes.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", asignacionDocentes.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname", asignacionDocentes.UserId);

            return View(asignacionDocentes);
        }

        // POST: AsignacionDocentes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CursoId,GrupoClasesId,UserId")] AsignacionDocentes asignacionDocentes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asignacionDocentes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", asignacionDocentes.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", asignacionDocentes.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", asignacionDocentes.UserId);
            return View(asignacionDocentes);
        }

        // GET: AsignacionDocentes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AsignacionDocentes asignacionDocentes = db.AsignacionDocentes.Find(id);
            if (asignacionDocentes == null)
            {
                return HttpNotFound();
            }
            return View(asignacionDocentes);
        }

        // POST: AsignacionDocentes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AsignacionDocentes asignacionDocentes = db.AsignacionDocentes.Find(id);
            db.AsignacionDocentes.Remove(asignacionDocentes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Controllers/EvaluacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;

namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario2")]

    public class EvaluacionesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Evaluaciones
        public ActionResult Index()
        {
            var evaluaciones = db.Evaluaciones.Include(e => e.Curso).Include(e => e.User);
            return View(evaluaciones.ToList());
        }

        // GET: Evaluaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso");
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname");

            return View();
        }

        // POST: Evaluaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CursoId,UserId,Convocatoria,Trabajo1,Trabajo2,Trabajo3,Test,Practica")] Evaluaciones evaluaciones)
        {
            if (ModelState.IsValid)
            {
                db.Evaluaciones.Add(evaluaciones);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", evaluaciones.UserId);
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname", evaluaciones.UserId);

            return View(evaluaciones);
        }

        // POST: Evaluaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CursoId,UserId,Convocatoria,Trabajo1,Trabajo2,Trabajo3,Test,Practica")] Evaluaciones evaluaciones)
        {
            if (ModelState.IsValid)
            {
                db.Entry(evaluaciones).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", evaluaciones.CursoId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "Name", evaluaciones.UserId);
            return View(evaluaciones);
        }

        // GET: Evaluaciones/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }

        // POST: Evaluaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            db.Evaluaciones.Remove(evaluaciones);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Controllers/MatriculasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;
using Microsoft.AspNet.Identity;


namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario2")]

    public class MatriculasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Matriculas
        public ActionResult Index()
        {
            int grupo = getGrupoClase();

            var matriculas = db.Matriculas.Include(m => m.Curso).Include(m => m.GrupoClases).Include(m => m.User).Where(p => p.GrupoClases.Id == grupo).ToList();

            return View(matriculas.ToList());
        }

        // GET: Matriculas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matriculas matriculas = db.Matriculas.Find(id);
            if (matriculas == null)
            {
                return HttpNotFound();
            }
            return View(matriculas);
        }

        // GET: Matriculas/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso");
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo");
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname");

            return View();
        }

        // POST: Matriculas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CursoId,GrupoClasesId,UserId")] Matriculas matriculas)
        {
            if (ModelState.IsValid)
            {
                db.Matriculas.Add(matriculas);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", matriculas.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", matriculas.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", matriculas.UserId);
            return View(matriculas);
        }

        // GET: Matriculas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matriculas matriculas = db.Matriculas.Find(id);
            if (matriculas == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", matriculas.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", matriculas.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users.OrderBy(e => e.NameSurname), "Id", "NameSurname", matriculas.UserId);

            return View(matriculas);
        }

        // POST: Matriculas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CursoId,GrupoClasesId,UserId")] Matriculas matriculas)
        {
            if (ModelState.IsValid)
            {
                db.Entry(matriculas).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Cursos, "Id", "Cod_Curso", matriculas.CursoId);
            ViewBag.GrupoClasesId = new SelectList(db.GrupoClases, "Id", "Cod_Grupo", matriculas.GrupoClasesId);
            ViewBag.UserId = new SelectList(db.Users, "Id", "NameSurname", matriculas.UserId);
            return View(matriculas);
        }

        // GET: Matriculas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Matriculas matriculas = db.Matriculas.Find(id);
            if (matriculas == null)
            {
                return HttpNotFound();
            }
            return View(matriculas);
        }

        // POST: Matriculas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Matriculas matriculas = db.Matriculas.Find(id);
            db.Matriculas.Remove(matriculas);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private int getGrupoClase()
        {
            string currentUserId = User.Identity.GetUserId();
            var grupos = db.AsignacionDocentes.Where(p => p.UserId == currentUserId).ToList();
            if (grupos.Count == 0)
                return -1;
            else return grupos.First().GrupoClases.Id;
        }
    }
}

AppGestionEMS/AppGestionEMS/Controllers/MisEvaluacionesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AppGestionEMS.Models;
using Microsoft.AspNet.Identity;


namespace AppGestionEMS.Controllers
{
    [Authorize(Roles = "tipoUsuario3")]

    public class MisEvaluacionesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: MisEvaluaciones
        public ActionResult Index()
        {
            string currentUserId = User.Identity.GetUserId();
            var evaluaciones = db.Evaluaciones.Include(e => e.Curso).Include(e => e.User).Where(p => p.UserId == currentUserId); ;
            return View(evaluaciones.ToList());
        }

        // GET: MisEvaluaciones/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Evaluaciones evaluaciones = db.Evaluaciones.Find(id);
            if (evaluaciones == null)
            {
                return HttpNotFound();
            }
            return View(evaluaciones);
        }
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AppGestionEMS/AppGestionEMS/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de";
}

<div id="header">
    <div class="flexslider">
        <ul class="slides">
            <li class="slider-item" style="background-image: url('/Content/images/slider/team.jpg')">
                <div class="intro container">
                    <div class="container-overlay">
                        <h1>ETSISI EM-Agency</h1>
                        <h2>Nuestro equipo</h2>
                        <h3>ETSISI EM-Agency trabaja ti</h3>
                        <h3>Deja tu proyecto en nuestras manos</h3>
                    </div>
                </div>
            </li> <!-- /.slider-item -->
        </ul> <!-- /.slides -->
    </div> <!-- /.flexslider -->
</div> <!-- /#header -->


<div class="container">
    <div class="row">
        <div class="scrollpost col-sm-3 col-xs-12 col-md-3 col-lg-3 px-0">
            <img src="/Content/images/foto_davidm.jpg" class="rounded-circle img-raised">
            <h4 style="text-align: center;">David Martín Diez de Oñate</h4>
        </div>
        <div class="scrollpost col-sm-3 col-xs-12 col-md-3 col-lg-3 px-0">
            <img src="/Content/images/foto_vop.jpg" class="rounded-circle img-raised">
            <h4 style="text-align: center;">Víctor M. Octavio Palomares</h4>
        </div>
        <div class="scrollpost col-sm-3 col-xs-12 col-md-3 col-lg-3 px-0">
            <img src="/Content/images/foto_dvl.jpg" class="rounded-circle img-raised">
            <h4 style="text-align: center;">David Velasco Laranjinha</h4>
        </div>
        <div class="scrollpost col-sm-3 col-xs-12 col-md-3 col-lg-3 px-0">
            <img src="/Content/images/foto_yuste.jpg" class="rounded-circle img-raised">
            <h4 style="text-align: center;">&nbsp;Javier &nbsp;Yuste &nbsp;Moure</h4>
        </div>
    </div>

</div>

AppGestionEMS/AppGestionEMS/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}

<div id="header">
    <div class="flexslider">
        <ul class="slides">
            <li class="slider-item" style="background-image: url('/Content/images/slider/contact.jpg')">
                <div class="intro container">
                    <div class="container-overlay">
                        <h1>ETSISI EM-Agency</h1>
                        <h2>Nuestro equipo</h2>
                        <h3>¿Tienes alguna pregunta o comentario? Envíanos un mensaje</h3>
                        <h3>No compartiremos su correo electrónico ni revelaremos su identidad secreta</h3>
                    </div>
                </div>
            </li> <!-- /.slider-item -->
        </ul> <!-- /.slides -->
    </div> <!-- /.flexslider -->
</div> <!-- /#header -->

<hr />

<section class="contacts section-wrapper">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="contact">
                    <div class="contact-icon">
                        <i class="ion-android-map"></i>
                    </div>
                    <div class="contact-name">
                        Dirección
                    </div>
                    <div class="contact-detail">
                        Calle Alan Turing s/n  <br>
                        (Carretera de Valencia Km 7) <br>
                        28031 Madrid <br>
                        España
                    </div>
                </div> <!-- /.contact -->
            </div>
            <div class="col-sm-4">
                <div class="contact">
                    <div class="contact-icon">
                        <i class="ion-ios-telephone"></i>
                    </div>
                    <div class="contact-name">
                        Teléfono
                    </div>
                    <div class="contact-detail">
                        Secretaría: 91 067 35 24<br>
                        Teléfono Conserjería: 91 067 35 34
                        <br><br><br>
                    </div>
                </div> <!-- /.contact -->
            </div>
            <div class="col-sm-4">
                <div class="contact">
                    <div class="contact-icon">
                        <i class="ion-email"></i>
                    </div>
                    <div class="contact-name">
                        Correo electrónico
                    </div>
                    <div class="contact-detail">
                        <br>
                        Secretaría:   <a href="mailto:negociado.alumnos@etsisi.upm.es">negociado.alumnos@etsisi.upm.es</a><br><br>
                        <br>
                    </div>
                </div> <!-- /.contact -->



            </div>

        </div>     <!-- /div del row -->
    </div>

</section>

AppGestionEMS/AppGestionEMS/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Página de inicio";
}

<div id="header">
    <section class="slider">
        <div class="flexslider">

            <ul class="slides">
                <li class="slider-item" style="background-image: url('/Content/images/slider/uno.jpg')">
                    <div class="intro container">
                        <div class="container-overlay">
                            <h1>ETSISI EM-Agency</h1>
                            <h2>Gestión integral de Notas</h2>
                            <h3>Toda la información para el profesor y el alumno a un click</h3>
                        </div>
                    </div>
                </li> <!-- /.slider-item -->
                <li class="slider-item" style="background-image: url('/Content/images/slider/dos.jpg')">
                    <div class="intro container">
                        <div class="container-overlay">
                            <h1>ETSISI EM-Agency</h1>
                            <h2>Gestión integral de Notas</h2>
                            <h3>Toda la información para el profesor y el alumno a un click</h3>
                        </div>
                    </div>
                </li> <!-- /.slider-item -->
            </ul> <!-- /.slides -->
        </div> <!-- /.flexslider -->
    </section> <!-- /.slider -->

</div> <!-- /#header -->

<hr />

<div class="container container-fluid">

    <div class="row">
        <div class="col-md-6">
            <div class="bloquemargen">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <a href="@Url.Action("Index", "AsignacionDocentes" )">
                            <img src="/Content/images/docentes.jpg" alt="Rounded Image" class="rounded img-raised img-fluid ">
                        </a>
                    </div>
                    <div class="col-md-6"></br></br></br></br>
                        <a href="@Url.Action("Index", "AsignacionDocentes" )">
                            <h3 class="title">
                                Asignación docentes
                            </h3>
                        </a>
                        <p>Actualiza los docentes de cada curso y grupo</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bloquemargen">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <a href="@Url.Action("Index", "Matriculas" )">
                            <img src="/Content/images/matriculas.jpg" alt="Rounded Image" class="rounded img-raised img-fluid ">
                        </a>
                    </div>
                    <div class="col-md-6"></br></br></br></br>
                        <a href="@Url.Action("Index", "Matriculas" )">
                            <h3 class="title">
                                Matrículas
                            </h3>
                        </a>
                        <p>Actualiza los alumnos matriculados en cada curso y grupo</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bloquemargen">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <a href="@Url.Action("Index", "Evaluaciones" )">
                            <img src="/Content/images/evaluaciones.jpg" alt="Rounded Image" class="rounded img-raised img-fluid ">
                        </a>
                    </div>
                    <div class="col-md-6"></br></br></br></br>
                        <a href="@Url.Action("Index", "Evaluaciones" )">

                            <h3 class="title">
                                Evaluaciones
                            </h3>
                        </a>
                        <p>Actualiza los resultados de la evaluación de los alumnos matriculados en cada curso y grupo</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="bloquemargen">
                <div class="row">
                    <div class="col-md-6 text-center">
                        <a href="@Url.Action("Index", "MisEvaluaciones" )">
                            <img src="/Content/images/misevaluaciones.jpg" alt="Rounded Image" class="rounded img-raised img-fluid ">
                        </a>
                    </div>
                    <div class="col-md-6"></br></br></br></br>
                        <a href="@Url.Action("Index", "MisEvaluaciones" )">
                            <h3 class="title">
                                Mis evaluaciones
                            </h3>
                        </a>
                        <p>Consulta el resultado de las evaluaciones de un alumno</p>
                    </div>
                </div>
            </div>
        </div>

    </div>



</div>

<script type="text/javascript">

                $(function () {
                    SyntaxHighlighter.all();
                });
                $(window).load(function () {
                    $('.flexslider').flexslider({
                        animation: "slide",
                        slideshowSpeed: 400,
                        start: function (slider) {
                            $('body').removeClass('loading');
                        }
                    });
                });


</script>